# Generated by Django 4.1.2 on 2022-10-13 21:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.CharField(max_length=200)),
                ('age', models.PositiveSmallIntegerField(null=True)),
                ('weight', models.DecimalField(decimal_places=2, max_digits=4, null=True)),
                ('story', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('image', models.CharField(max_length=200)),
                ('release_date', models.DateField(null=True)),
                ('rating', models.DecimalField(decimal_places=1, max_digits=2, null=True)),
                ('characters', models.ManyToManyField(to='api.character')),
                ('genre', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api.genre')),
            ],
        ),
    ]
